# waypoints.yaml
# 格式：[x, y, z, qx, qy, qz, qw]
floor_4:
  map_name: "floor_4_raw.yaml" # 假设 4 楼地图名为这个
  stairs_point: [12.5, 4.8, 3.0, 0.0, 0.0, 0.0, 1.0]
  office_goal: [15.0, 6.0, 3.0, 0.0, 0.0, 0.0, 1.0] # 补全代码中调用的 key
  

floor_3:
  map_name: "LS_floor2.yaml" 
  stairs_point: [7.09, 0.72, 0.0, 0.0, 0.0, 0, 0]
  office_goal: [7.42, 0.0, 0.185, 0.0, 0.0, 0.0, 1.0] # 补全代码中调用的 key

# floor_3:
#   map_name: "floor3_raw.yaml" # 匹配 launch 文件中的默认值
#   stairs_point: [43.466, 11.962, 0.185, 0.0, -0.0, -0.2256, 0.9731] # 已经校准过
#   # office_goal: [40.0, 10.0, 0.185, 0.0, 0.0, 0.0, 1.0] # 补全代码中调用的 key

settings:
  floor_threshold: 2.5
  dist_threshold: 1.2

start_candidates:
  - [2.09, 0.72, 0.0, 0.0, 0.0, 0, 0]
# - [10.5, 5.2, 0.18, 0.0, 0.0, 0.0, 1.0]      
# - [2.0, -1.5, 0.18, 0.0, 0.0, 1.0, 0.0]     