# Multi-floor mission config
# Pose format: [x, y, z, qx, qy, qz, qw]


floors:
  0:
    map_name: "LS_123_floor0.yaml"
    stairs:
      s0: [-6.544,3.199, 0.0,  0.0, 0.0, 0.7432, 0.6690]
      s1: [-6.544,3.199, 0.0,  0.0, 0.0, 0.7432, 0.6690]
    goals:
      office_goal: [-6.544,3.199,  0.0, 0.0, 0.0, 0.7432, 0.6690]

  1:
    map_name: "LS_123_floor1.yaml"
    stairs:
      s0: [-6.811,4.758, 0.0, 0.0,  0.0, 0.7486, 0.6630]      
      s1: [-8.06,16.79, 0.0, 0.0,  0.0, 0.7486, 0.6630]

    goals:
      office_goal: [-6.811,4.758, 0.0, 0.0, 0.0, 0.7486, 0.6630]

  2:
    map_name: "LS_123_floor2.yaml"
    stairs:
      s0: [-8.06,16.79, 0.0, 0.0,  0.0, 0.7486, 0.6630]
      s1: [-8.06,16.79, 0.0, 0.0, 0.0, 0.7486, 0.6630]
    goals:
      office_goal: [-28.588, 5.10, 0.0, 0.0, 0.0, 0.74, 0.67]

stair_edges:
  - from_floor: 0
    from_stair: s0
    to_floor: 1
    to_stair: s1
    z_offset: -4.58

  - from_floor: 1
    from_stair: s0
    to_floor: 2
    to_stair: s1
    z_offset: -8.86

settings:
  initial_floor: 0
  floor_z_offsets:
    0: 0.0
    1: -4.58
    2: -8.86

start_candidates:
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.00, 1.00]
